### ISSUE TITLE
Suggestion: Editable invitation text

### ISSUE THREAD

**Issue by bfriesenvcc** [michael-milette/moodle-enrol_invitation#2]
The email message sent out includes two parts: The plugin message followed by the Message from instructor. See below.

The current message is a bit confusing (e.g. why does it say "on location?"). It would be nice if the plugin message was editable by the Administrator through system settings or through Moodle's language customization string. Currently, there is no string (as far as I could tell).

Alternatively, just remove the "on location" part, since this sends an invitation for an online course as well as the dates, since the Moodle end date is not mandatory and if it's missing it shows 1969.

Here's a sample message, as it is now:

<img width="380" alt="InvitationMessage" src="https://user-images.githubusercontent.com/8193384/146592368-a3cb17ab-5a3c-4fa4-8b27-d3b2ed38cdbe.PNG">

**Comment by michael-milette** [comment]
Hi @bfriesenvcc ,

It is indeed weird that it says "on location" for an online LMS.

Fortunately the text is indeed editable. It is just a little harder to find since you don't actually see the text appear on the screen with the strings=1 option enabled and the parameter added to the URL. Here is how to make the change in Moodle as a Site Administrator:

1. Go to **Site Administration > Language > Language Customization**
2. Choose the language in which you want to make the change.
3. Click the **Open Language Pack for Editing** button
4. Once the language pack has finished loading, click the **Continue** button.
5. In the **Show strings for the these components** field, click on **enrol_invitation**.
6. In the **String identifier** field, enter **emailmsgtxt**.
7. Click the **Show strings** button.

You should now see the default text for the message.

For more information on customizing language strings in Moodle, see:
https://docs.moodle.org/en/Language_customization

### For Multi-Language Moodle Sites

If you have more than one language on your site, be sure to repeat the process above for each language. Also, please note that the message will be sent in the current UI language. If you want to send some invitations in English and some in French, for example. you will need to do it in two passes, making sure to change the user interface language in between. 

Hope you found this helpful.

Best regards,

Michael

**Comment by bfriesenvcc** [comment]
I must be doing something wrong. I chalk it up to being in a last minute rush before the Christmas break.
<img width="390" alt="filterstrings" src="https://user-images.githubusercontent.com/8193384/146618814-61ba3e35-cc81-41df-ba2f-4b0b1bc3d6da.PNG">

**Comment by bfriesenvcc** [comment]
OK, something is wrong on our end.

I uninstalled the and reinstalled and the same thing happens. However, when I install the same on my local Windows installation, it works as expected. So, I guess it's definitely my problem and not yours. 

Thanks, and sorry for bothering you with this!

**Comment by michael-milette** [comment]
No worries,

**Comment by michael-milette** [comment]
I looked into that sentence. It seems that back in 2019, there was an Events course format plugin which had a Location field. This is what should have appeared between "on location" and the period (full stop) after that:
https://moodle.org/plugins/format_event

It doesn't seem to have ever been developed beyond compatibility with Moodle 3.2 to 3.5 and obviously didn't handle the situation where someone might have been using some other course format.

I re-opened this ticket and will be fixing this issue. I am thinking of replacing the location with one of the following:

- A **Location** custom course field, if it exists; OR;
- "Online"; OR
- Just re-wording the string so that does not try (and sometimes fail) to specify a location.

Thoughts?

Michael

**Comment by michael-milette** [comment]
Hi @bfriesenvcc 

As for the string, I am not sure what to tell you. It is there for me. Make sure that there is no leading or trailing space around "emailmsgtxt". Also, try typing it in instead of copying and pasting. Sometimes extra invisible characters sneak in from the clipboard.

![image](https://user-images.githubusercontent.com/3808579/146626955-f54e2b94-aa7e-44d7-9abe-d9b9059a9ea7.png)

Alternatively, don't put anything in the **String Identifier** field and click **Show strings**. You will need to scroll down the page to find the string.

Best regards,

Michael

**Comment by michael-milette** [comment]
Try purging the cache on your Linux machine. I just installed it on Linux on Moodle 3.9 and it worked. That was the source of my screenshot.

**Comment by bfriesenvcc** [comment]
> I re-opened this ticket and will be fixing this issue. I am thinking of replacing the location with one of the following:
> * A **Location** custom course field, if it exists; OR;
> * "Online"; OR
> * Just re-wording the string so that does not try (and sometimes fail) to specify a location.
> Thoughts?

IMO, the more generic, the better. So I would avoid the location.

**Comment by bfriesenvcc** [comment]
Nothing I do on our development server shows me the string. But, it works fine on my local installation. I'm not able to purge cache since I don't have that level of access. The best I could do was use the "purge all caches" interface within Moodle. That didn't work. I'll keep poking away at it to see what's going on, but it's our issue, not yours. :-)

**Comment by bfriesenvcc** [comment]
Thanks, Michael.

I don't know what's going on on my end, but I just cannot find the language strings for this plugin. I see them in the enrol_invitation file, yet they just won't show up on the customlang page (see image) -- even after an uninstall, reinstall, and cache clearing. I've never seen this issue before but, like I mentioned previously, this must be something on my end, when I have more time.

<img width="455" alt="customlang" src="https://user-images.githubusercontent.com/8193384/149188614-7a00a95a-b658-4738-b73b-5d4329d1646f.PNG">
.

**Comment by michael-milette** [comment]
FYI: Here is an example of the text for the new email invitation message:

![image](https://user-images.githubusercontent.com/3808579/149221214-3bb74842-4128-4d35-9a10-a8ebd74232ec.png)

Let me know if you have any suggestions.

Michael
