### ISSUE TITLE
Wrong URL in string id 'defaultsubjectformat_desc'?

### ISSUE THREAD

**Issue by pete1854** [michael-milette/moodle-enrol_invitation#26]
Hi again,

The URL referenced in
https://github.com/michael-milette/moodle-enrol_invitation/blob/570af108f9f8f21d34172f4d024d68be404a70d9/lang/en/enrol_invitation.php#L111
```../tool/customlang/```

results in a 404 message.

I've changed it to ```../admin/tool/customlang/``` in our environment to make it work. If you intended to reference the language customization page I believe this should be the URL to use in the language file. Is this correct or have I misunderstood the intention?

Kind regards,
Peter

**Comment by michael-milette** [comment]
Hi @pete1854 ,

Thanks again for sharing a fix. Your suggestion was spot on (of course) and has now been added here on GitHub. Please give the updated version a try and, if you would be so kind, let me know if it now works as expected.

Best regards,

Michael

**Comment by pete1854** [comment]
Hi @michael-milette,

Thanks once again for your quick and kind response! I'm happy to contribute when I can. I find your plug-in very useful and it feels well crafted (as opposed to many other modules). The invitation messages created are very nice looking and easy to understand!

I have tested your fix and can confirm it works as expected.

BTW - I might come up w/ a PR suggesting to expose some functionality through the web service API. We have a separate UI for managing enrolment (since many of my coworkers find the native UI of Moodle as such too cumbersome to work with). I'm thinking of extending the use of your plugin by sending out invitations (via your plug-in) using the Moodle WS API once the users are added through our custom UI. For that I will need to be able to have your plug-in enrol users via a REST HTTP call.

I'll get back once I have something in the works.

Kind regards,
Peter

**Comment by michael-milette** [comment]
Hi Peter,

Thank you. However, I did not write the plugin. It had been abandoned since about 3 years and I only recently adopted it a couple of months ago. The original author should get lot of the credit.

Since taking it over, I've updated the code to make it compatible with current versions of Moodle, merged in code from several forks of the code, fixed bugs, improved multi-language support and accessibility, and clarified language and made it more consistent and generic so that it could be useful in a variety of environments.

All this to say that the current version is the result of the effort by several contributors like you over the years.

If you look at the list of recent commits, you may notice that you were listed as a co-creator for each of the solutions you provided. I really appreciate your efforts as I am still getting to know the code myself. Thank you again.

Best regards,

Michael
