### ISSUE TITLE
Problems with default values

### ISSUE THREAD

**Issue by atrolex** [michael-milette/moodle-enrol_invitation#30]
I have just installed moodle 4.0.1+ (stable)

I have this configuration within enrollment methods:
![image](https://user-images.githubusercontent.com/33658481/173182691-2bf2620e-1364-4190-bf49-022dfc712458.png)
so dafault values are activated.

If I try to send some invitation via this form with some custom text:
![image](https://user-images.githubusercontent.com/33658481/173182754-8d12b6b2-0a6e-46bc-8afb-dc20fa04ebfd.png)

I have received such email:
![image](https://user-images.githubusercontent.com/33658481/173182796-90839ede-d0a3-4450-a971-6920157d23b0.png)

I see the following problems:
1) Default value for the Enrollment method "Invitation", was not applied to the invitation form - it is always empty as I open it. I expect it to be filled with the default values.
2) The text I have added manually to the invitation form was not sent, I received standard message, which was not my default.
3) The is no possibility to edit Subject on the invitation form, if "Use invitation with default values" is set to "Yes".

**Comment by michael-milette** [comment]
Hi @atrolex ,

Thank you for reporting this issue. I will look into it as soon as I have a chance and get back to you.

Best regards,

Michael

**Comment by atrolex** [comment]
Hi @michael-milette thank you!
I have also noticed, that no account is created for the envitee, if the envitee clicks on the accept button. Is is a bug or should it be so? 
My use case is - I want to invite different people to take part in a quiz without creating an account for them manually. I expect the system to create account for them automatically.

**Comment by michael-milette** [comment]
Hi @atrolex 

First, I wanted to let you know that I have confirmed your bug report and am able to reproduce the issue. I also noticed that, if you have debugging enabled in Moodle, an error is displayed which may or may not be related.

    get_extra_user_fields() is deprecated. Please use the \core_user\fields API instead.
    line 3321 of \lib\deprecatedlib.php: call to debugging()
    line 367 of \enrol\invitation\invitation_form.php: call to get_extra_user_fields()
    line 214 of \lib\formslib.php: call to invitation_email_form->definition()
    line 90 of \enrol\invitation\invitation.php: call to moodleform->__construct()

There should not normally be this or any error and the default message should work.

As for your most recent question, **Invitation** is just an enrolment plugin that enrolls users in courses. It does not create user accounts. If you think about it, an email address is not enough information to create an account in Moodle. It would need the user's first name, last name, password, etc. - All the information that you or the learner usually enter when they create an account.

The advantage of this plugin is that you can enroll users in a course whether or not they have an account on the site. If they don't have an account, they will be enrolled in the course automatically once they create an account. If the user already has an account, they just need to click the link in the email and log into the site to find themselves automatically enrolled in the course.

Perhaps, a future enhancement might be to redirect the user to the account registration page instead of the login page if the user does not already have an account. What do you think?

Thank you again for reporting the issues. I will be fixing both of the compatibility issues and will notify you once they have been fixed.

Best regards,

Michael

**Comment by michael-milette** [comment]
Note: This bug affects Moodle 3.11 and 4.0.

**Comment by michael-milette** [comment]
Hi @atrolex ,

If "Use invitation with default values" is set to "Yes", then the only fields that should be appearing are the ones where you enter the email address. The fact that the "message" field is appearing is an error. It should not be in this case.

In order to be able to edit the subject and/or be able to enter a message at the time you are sending it, you must set the "Use invitation with default values" field to "No".

In the version here on GitHub, I have fixed the following:

- The displayed source code error has been fixed.
- The message field no longer appears when "Use invitation with default values" is set to "Yes"
- The default message is included in the email when "Use invitation with default values" is set to "Yes"

If you would be so kind, I would really appreciate it if you could test it out and ensure that the issues have been resolved. If they have, these bug fixes will be released on Moodle.org shortly.

If you feel that you would like to see the default values work in a different way, please feel free to open a new "Feature Request" ticket for consideration.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @atrolex ,

Thanks for the update. I will look into adding support for filters. I remember applying the filters but it may not be working for both default and custom messages.

As for the rest, it seems to be working as designed. If you want to change the rest of the contents of the template, you can customize it by editing the strings in the language pack of the plugin using the Language editor included in Moodle. Take a look at the README.md file included with the plugin. You will find a list of several custom tags, including things like first and last name, that you can insert into the template.

You may even discover that you don't need to use FilterCodes at all for this.

I will let you know as soon as I have fixed support for FilterCodes.

Best regards,

Michael

**Comment by michael-milette** [comment]
Keep in mind that making changes to the language pack will affect all instances of Invitation on the Moodle site, not just for your course.

**Comment by michael-milette** [comment]
Hi @atrolex ,

The problem with using tags like {firstname}, {surname} and {email} from FilterCodes is that these get replaced with the profile information of the person sending the message, not the person being invited.

I just added a few new plain text tags to the Invitation plugin:

- {$a->email} : Invitees email address - always available.
- {$a->username} : Invitees username - only available if the user already has an account on the site, otherwise blank.
- {$a->firstname} : Invitees first name - only available if the user already has an account on the site, otherwise blank.
- {$a->lastname} : Invitees last name - only available if the user already has an account on the site, otherwise blank.
- {$a->surname} : This is an alias for {$a->lastname}.

If you upgrade to the latest version here on GitHub, these will be available as well as all of the other {$a->...} tags listed in the **Email template customization** section of README.md.

In addition, please note that the custom message now supports HTML.

If you have a chance, I would be thankful if you would be so kind as to try out this latest version. If it works for you, I will include these changes in an upcoming release of Invitation.

Best regards,

Michael

**Comment by atrolex** [comment]
Thank you, Michael!

**Comment by michael-milette** [comment]
Thank you!
