### ISSUE TITLE
Bug: user invitation select users message does not override translation

### ISSUE THREAD

**Issue by gemguardian** [michael-milette/moodle-enrol_invitation#36]
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [ ] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

while testing we found out that when we **select** users at the invitation user option, the message that is being send 'parcing' in the translation text but keeps the 'coded' text. This will cause confusion when you send this invitation this way.

### What do you think should have happened?

I expected that the message php file has a bug for not correctly dealing with lokale language changes, 

### Steps to reproduce

1. Login as 'teacher'
2. Go to 'course'
3. Click on 'participants
4. click on Invite users
5. Selected the users you want to send the invitation to
6. send invitation

### Screenshots

![2023-07-12_10-55-32](https://github.com/michael-milette/moodle-enrol_invitation/assets/16559999/1b4f6740-0dc4-4a1e-ab3d-af9fa62fb675)

### Moodle version

4.1.4

### Installed Moodle UI Language packs.

- [ ] English only
- [ ] One or more other languages/regional dialects (specify below)
- [X] Other

### If other language(s), please specify

Dutch

### Workaround

We don't use this option, we only copy/paste emailadress in the top. 

### System information

Client Device type:desktop
Client Operating System: Windows
Client Web Browser: chrone
Server Operating System: linux
Server Webserver: Apache
Server PHP: 7.4

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @gemguardian ,

I suspect that your issue is one of the following.

Was the Moodle UI in Dutch when you sent the invitation or in English? 

- If it was in English, that is why some of the text appears in Dutch. 
- If it was in Dutch, you will need to contribute some Dutch translations in order to resolve the issue. You can do this by going to https://lang.moodle.org/ and submitting your translations in AMOS, the Moodle language repository. Once you submit the Dutch translations in AMOS, it may take a few days for the changes to be reviewed and accepted by the maintainer of the Dutch language pack, and then distributed to your Moodle site. By submitting translations, you will not only be helping yourself but everyone who uses Moodle and the Invitation plugin in Dutch.

The only language pack that is included with the Invitation plugin is English. Support for translations in other languages is provided by community contributions. As you can see on the following page, only about 14% of the plugin has been translated into Dutch:
https://moodle.org/plugins/enrol_invitation/translations

Just remember to switch the Moodle UI language to Dutch and your emails should appear in the Dutch language.

Hope you find this information useful.

Best regards,

Michael Milette

**Comment by gemguardian** [comment]
@michael-milette I had the text translated to Dutch locally , as I wrote in my comment. But surelly we will commmit the translated strings to Amos. :)
